### ISSUE TITLE
No SD card permission if apk installed before inserting SD Card

### ISSUE THREAD

**Issue by j-waaang** [MrBoboFace/QuestPlayer#1]
Just noticed that SD card access permission is asked before installing the app. If you enter your SD card with the qsp game after the app has been installed, the app has no access to the card. Reistalling the app helps. Maybe add function to reask permission in App?

I have a Motorola Moto Z with Android 7.1.1. Everthing else seems to work fine.

**Comment by MrBoboFace** [comment]
QuestPlayer assumes the user will use an external SD card when first installed, but switches the "Use External SD Card" setting to "OFF" if one is not found. If an SD card is inserted later, the user should be able to manually switch to external storage in Settings (set "Use External SD Card" to "ON").
