### ISSUE TITLE
Access to save files outside of app (e.g. via file manager)?

### ISSUE THREAD

**Issue by j-waaang** [MrBoboFace/QuestPlayer#2]
Is the app save file compatible with the windows version of qsp player? The save file doesnt seems to be accessable outside of the app (e.g. via file manager)? It would be great if I can put the save file into gdrive/onedrive and play the save file on pc too.

I hope its ok to use the Issues for asking questions.

**Comment by MrBoboFace** [comment]
Save files are compatible between Android and Windows versions (as far as I can tell). They are created and loaded in the same manner, so it should be fine.

All save files are placed in Documents/QSP_saves on the main storage. You should be able to find your save files there in the folder associated with your game.
