### ISSUE TITLE
Immident crash when tries to download game on list / Games arent gettin displayed which in SD card

### ISSUE THREAD

**Issue by tempacc123** [MrBoboFace/QuestPlayer#3]
Currently im using samsung S7 Edge, Android 6.0.1 

This app just crashes when i tried to use this for playing some games.

**Comment by MrBoboFace** [comment]
After some work, I have rewritten the system so Quest Player 2.0 can download and play games properly. I have also changed it so the save file directory is the same as the game directory (whichever that is).

**Comment by tempacc123** [comment]
ah, thanks!
